driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
    run_list: apt::default
  - name: debian-8.1
    run_list: apt::default
  - name: fedora-21
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
- name: lwrp_x509
  run_list:
  - recipe[test::lwrp_x509]
- name: lwrp_dhparam
  run_list:
  - recipe[test::lwrp_dhparam]
- name: lwrp_rsa_key
  run_list:
  - recipe[test::lwrp_rsa_key]
